# Generated by Django 4.2.5 on 2023-09-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, upload_to='attributions/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, upload_to='attributions/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='license2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='license3',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
